version: "3.8"
services:
  # result:
  #   build: ./ResultContainer
  #   ports:
  #     - 3001:3001
  portal:
    build: .
    ports:
      - 4000-4050:3000
    volumes:
      - ./src:/app/src
  nginx:
    container_name: nginx_2.0
    restart: always
    build: ./reverse_proxy
    ports:
      # Dev
      # - 1337:80
      # Prod
      - 8080:8080
      # - 443:443
    depends_on:
      - portal
   
  # reverse-proxy:
  #   image: nginx:1.17.10
  #   container_name: reverse_proxy_demo
  #   depends_on:
  #     - login
  #   volumes:
  #     - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 8080:8080

